### ISSUE TITLE
Week 12 Project Assignment Feedback

### ISSUE THREAD

**Issue by emily1129** [Latin-Developers/api-ufeeling#2]
1. Use `include Dry::Monads::Result::Mixin` when the Service Object has one step only.
https://github.com/Latin-Developers/api-ufeeling/blob/cf819e7a5044db4b725c779f033698a100a51783/app/application/services/get_comments.rb#L9-L11
https://github.com/Latin-Developers/api-ufeeling/blob/cf819e7a5044db4b725c779f033698a100a51783/app/application/services/get_video.rb#L9-L11

**Comment by Cesar64-Garcia** [comment]
@emily1129 Is this actually scalable for long term? Because if at some point we need to add a new step we will need to refactor the whole file to handle steps, which will mean rework. 

Also, for maintainability I consider is better to all the services to look the same, it's easier to understand and maintain, specially for new members.

**Comment by soumyaray** [comment]
Hi folks, I'm fine with both approaches.  I realize I promoted using a plain old Ruby object (PORO!) when there is only one step, as @emily1129  said.  But @Cesar64-Garcia's arguments make perfect sense to me.

**Comment by Cesar64-Garcia** [comment]
Thanks for the reply, most of our services ended up with multiple steps.
